image: "node:latest"

stages:
- build
- pages

build:
  stage: build
  script:
  - npm install
  - npm run export:site
  artifacts:
    name: dist
    expire_in: 7d
    paths:
    - dist/

pages:
  stage: pages
  dependencies:
  - build
  script:
  - mv dist public
  artifacts:
    paths:
    - public/
  only:
  - master